### ISSUE TITLE
Bump node-sass version

### ISSUE THREAD

**Issue by tropperstyle** [lasso-js/lasso-sass#1]
The node-sass dependency is stuck at a pre-1.0 version while current stable is 3.x. I tried using iojs, but couldn't compile this older version of node-sass so I settled on node --harmony. Then I tried to use node-bourbon, but that failed too due to the old incompatible version of node-sass. I forked this repo to allow the latest version: https://github.com/tropperstyle/lasso-sass/commit/15e2eb5bde120aa36d21763ac69f7c227e0b2cda but then whenever it tries to compile a scss file, it just hangs and eventually times out without any error messages.

**Comment by patrick-steele-idem** [comment]
Hi @tropperstyle, I have no objections to upgrading to the latest version of node-sass. If you are able to get it working please submit a PR. I suspect that the API has changed since the `pre-1.0` release. Would you be interested in reviewing the latest docs for [node-sass](https://github.com/sass/node-sass) to see if there needs to be a code change to the `lasso-sass` plugin?

**Comment by austinkelleher** [comment]
This issue was opened a long time ago, and it has since been fixed, so I am going to close it out.
